### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Deeksha2501** [tusharnankani/TSECHackathon#4]
I've provided wrong Contact number(for testing) and Obviously I didn't get the OTP but somehow I still manage to access the portal because the OTP was shown in the developer console.
This is a small mistake but can fail the whole security mechanism
Can I remove that from the code?

**Comment by tusharnankani** [comment]
Hi @Deeksha2501! We appreciate your concern about security! 

Now, since this a prototype, we *have not* used any paid tool, hence, the OTP isn't sent to your phone number, and is instead displayed on the console for testing purposes. If this website is used in the real world, for proper use, even if someone enters a wrong phone number, he won't be able to log in, until he enters the right OTP sent on his phone number.

Though, we have implemented simpler checks for now like check for 10-digit phone number etc. 

Also, for a further secure service, we take in their *Aadhar Card number* for now, but we do plan to implement, for further verification, if the entered phone number and the entered phone number match. 

I hope this answers your question, if you plan to make some changes in the code, go ahead and make a PR! 🤗
We will definitely look into it!

Thank you!

**Comment by Deeksha2501** [comment]
Ohh.. I didn't know that was a template.
I liked the the whole concept of the website and want to contribute in any way I can.

**Comment by tusharnankani** [comment]
Hi @Deeksha2501 

This webapp is actually a prototype, it is not a *template*, Which was a part of one of the hackathons, we participated in. 
Though, do contribute in however way you want to! ^_^
I am closing this issue as of now! I hope I cleared your question!

Regards,
Tushar Nankani
